services:
  mysql:
    image: mysql:8.4
    container_name: neulbomgil-mysql
    restart: unless-stopped

    ports:
      - "3306:3306"

    environment:
      MYSQL_DATABASE: neulbomgil
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: neulbomgil-redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - redis-data:/data

volumes:
  mysql-data:
  redis-data:
